module.exports={
SARAH:{name:'Dr. Sarah',initial:'S',
 day:[['7:00','get_up','gets up'],['8:00','clinic','arrives at the clinic'],['8:30','see_patients','sees patients'],['10:00','examine','examines a patient'],['12:00','have_lunch','has lunch'],['1:00','see_patients','sees patients'],['4:00','records','checks medical records'],['6:00','finish_work','finishes work']],
 facts:[['Patients a day?','She sees 15 patients a day.'],['Sundays?',"She doesn't work on Sundays."],['At night?',"She doesn't work at night."],['Appointments?','Yes, she does. She has appointments in the afternoon.'],['After work?','She watches TV after work.'],['Bed?','She goes to bed at 11:00.']],
 questions:[['How many patients ',' she see a day?','does'],['',' she work on Sundays?','Does'],['',' she work at night?','Does'],['',' she have appointments in the afternoon?','Does'],['What ',' she do after work?','does'],['What time ',' she go to bed?','does']]},
BEN:{name:'Dr. Ben',initial:'B',role:"Dr. Sarah's colleague",facts:[['Where does he work?','He works at a hospital.'],['What time does he start?','He starts at 8:00 in the evening.'],['Does he work at night?','Yes, he does. He works at night.'],['How many patients does he see?','He sees about 20 patients a night.'],['Does he work on weekends?',"Yes, he does. He doesn't work on Mondays."],['What time does he finish?','He finishes at 6:00 in the morning.']]},
RW:[['He work in a clinic.',false,'He works in a clinic.'],['I works from Monday to Friday.',false,'I work from Monday to Friday.'],["She doesn't work at night.",true,''],['Does he works on Saturdays?',false,'Does he work on Saturdays?'],['Do you work at a hospital?',true,'']],
ROUTINE:[['get_up','get up'],['have_breakfast','have breakfast'],['go_to_work','go to work'],['start_work','start work'],['have_lunch','have lunch'],['take_a_break','take a break'],['finish_work','finish work'],['go_home','go home'],['watch_tv','watch TV'],['go_to_bed','go to bed']],
WORK:[['hospital','work at a hospital'],['clinic','work at a clinic'],['see_patients','see patients'],['examine','examine a patient'],['check_patient','check a patient'],['appointments','have appointments'],['records','check medical records'],['take_a_break','take a break'],['weekends','work on weekends']],
ROUND2:['What time do you start work?','Where do you work?','Do you see patients every day?','How many patients do you usually see?','Do you work on weekends?','What do you do after work?'],
FIX:["He don't work on Sunday.",'I works in a clinic.','Does she works there?','I am work at a hospital.','She finish at six.'],
STAGES:[[1,'Lead-in','What’s a typical day like for you?',4,'T↔S','1–2'],[2,'Diagnostic speaking','Tell me about your day',5,'S→T','3'],[3,'Vocabulary discovery',"A Doctor's Day",7,'T↔S','4–6'],[4,'Language discovery',"What's different?",7,'T↔S','7–8'],[5,'Quick accuracy challenge','Right or Wrong?',5,'T↔S','9'],[6,'Information gap','Who is it?',7,'S↔T','10–11'],[7,'Pronunciation micro-focus','He works',3,'T↔S','12'],[8,'Main communicative task','Doctor vs. Doctor',10,'S↔T','13–15'],[9,'Delayed correction','Can you fix it?',5,'T↔S','16'],[10,'Exit task','Tell me about your day',2,'S→T','17']],
};
