s=open('docs.js').read()
a0=s.index(" const proc=["); a1=s.index(" const procRows=")
proc=''' const proc=[
 ['Ask “What’s a typical day like for you?” Follow up only as needed: “What time do you get up? What do you do in the morning? What time do you start work?” Don’t correct. Start the error log.','Activate the topic; begin diagnosing spontaneous simple present.'],
 ['“Tell me about a normal weekday — morning to evening.” The student speaks along the day line. Support questions only when the student stops. Log errors.','Establish a baseline and identify priority errors.'],
 ['Introduce Dr. Sarah, the lesson’s doctor. S4: times + icons only — Look. Guess. Say it: “What does she do at 7:00?” S5: reveal the phrases; the student retells her day; ask the 3 questions. S6: “Which of these do you do? When?” — true sentences, including negatives.','Review/expand routine and work vocabulary; connect it to the target language; personalise.'],
 ['S7: show the pairs with no highlighting. Ask one question at a time: What’s different? Why “works”? Why doesn’t “work” change? What comes after “does”? S8: the student states the pattern; confirm with the slide. Point to DOES + HE + WORK.','Guided discovery of the form: 3rd-person -s; doesn’t / does + base verb.'],
 ['“Right or wrong? Fix the wrong ones.” The student corrects orally. Refer back to S8 rather than re-explaining.','Controlled accuracy practice.'],
 ['S10: “You know Dr. Sarah’s day at the clinic. There are six more things you don’t know. Ask me.” Answer ONLY the information requested. If a question is wrong, don’t answer: puzzled look / pause / elicit, and let the student self-correct. S11: question frames if needed; then “Tell me about Dr. Sarah.”','Meaningful do/does question practice with a genuine information gap; 3rd-person retelling.'],
 ['NOTICE works / lives / watches → LISTEN (model ×2) → REPEAT → USE: “Tell me about a colleague.” (If needed: “Where does he/she work? What does he/she do?”)','Intelligibility of 3rd-person -s (/s/ /z/ /iz/).'],
 ['SUPPORTED → PERSONALISED → INDEPENDENT. R1 (S13): the student interviews you about Dr. Ben, Dr. Sarah’s colleague. R2 (S14): you interview the student — choose 3–4 questions, not all six, and add natural follow-ups. R3 (S15): no prompts, 2–3 minutes of extended speaking. Monitor; don’t interrupt. During R3, type 3–5 real errors into S16.','Transfer the target language to personalised, then independent communication.'],
 ['BEFORE SHOWING: replace the backup examples with 3–5 real errors from the student. Show one at a time: “Is it right?” “Can you fix it?” Guided self-correction; no re-explanation unless absolutely necessary; never more than one target error per sentence. Close with the pattern box.','Address priority errors without disrupting fluency.'],
 ['“So, what does a typical day look like for you?” A short final check: 4–5 sentences, no help (not a repeat of Round 3). Check with the exit checklist (Appendix D). Next-time preview only (How often…?) — do not teach it now.','Check progress against the main aim.']];
'''
s=s[:a0]+proc+s[a1:]
b0=s.index(" const detail=["); b1=s.index(" const p1=`")
detail=''' const detail=[
 ['1 · Lead-in (4 min · slides 1–2)','“What’s a typical day like for you?”',['I wake up at six, I go to the hospital…','I am work in a clinic. (diagnostic)'],'I am work / I working; missing -s in any he/she mention.'],
 ['2 · Diagnostic speaking (5 min · slide 3)','“Tell me about a normal weekday — from the morning to the evening.”',['I get up at 6:30. I go to work by car. I see patients all morning…'],'Tense mixing (I went / I go); “I am…” + verb; he don’t (if they mention colleagues).'],
 ['3 · Vocabulary discovery (7 min · slides 4–6)','“This is Dr. Sarah. What does she do at 7:00? … and at 8:30?” → “Which of these things do you do? When?”',['She gets up. She arrives at the clinic. She sees patients…','No, she doesn’t. She works at a clinic. · She finishes at 6:00.'],'She see / she finish (no -s); “examinate”; “medical registers” for medical records.'],
 ['4 · Language discovery (7 min · slides 7–8)','“What’s different?” / “Why do we say ‘works’ here?” / “What happens after ‘does’?”',['Works — because it’s he.','After does — no s. / Does has the s.'],'The student may over-apply -s (Does he works?) or say “because present”. CCQ: “He — one person or more?” “Is ‘works’ OK after does?”'],
 ['5 · Right or wrong? (5 min · slide 9)','“Right or wrong? Fix the wrong ones.”',['1 wrong — He works… · 2 wrong — I work… · 3 right · 4 wrong — Does he work… · 5 right'],'If the student accepts sentence 4 as correct, point back to DOES + HE + WORK and elicit the correction.'],
 ['6 · Information gap (7 min · slides 10–11)','“You know Dr. Sarah’s day at the clinic. Six more things — ask me.” → “Now tell me about Dr. Sarah.”',['How many patients does she see a day? Does she work on Sundays? Does she work at night? Does she have appointments in the afternoon? What does she do after work? What time does she go to bed?','She sees 15 patients a day. She doesn’t work on Sundays…'],'How many patients she sees? / Does she works? / What time she go to bed? — withhold the answer until the question is well formed.'],
 ['7 · Pronunciation (3 min · slide 12)','“Listen — are the endings the same?” → “Tell me about a colleague.”',['works /s/ · lives /z/ · watches /iz/','My colleague works at the hospital. She lives near me.'],'Adding an extra syllable to works (“work-es”); dropping the -s completely.'],
 ['8 · Doctor vs. Doctor (10 min · slides 13–15)','R1 “Ask me about Dr. Ben — Dr. Sarah’s colleague.” · R2 “What time do you start work?” → “Every day?” → “What do you do first?” · R3 “Tell me about your typical working day.”',['Does he work at night? — Yes, he does.','At 8. — Every day? — Yes, Monday to Friday.','2–3 minutes of connected speech in R3.'],'Mixing do/does across rounds (Do he…?); dropping -s in fluent R3 speech.'],
 ['9 · Delayed correction (5 min · slide 16)','“Is it right? Can you fix it?” (one real error at a time)',['He doesn’t work on Sunday.'],'Correcting the wrong part — prompt with the pattern box, not an explanation.'],
 ['10 · Exit task (2 min · slide 17)','“So, what does a typical day look like for you?”',['4–5 spontaneous sentences'],'Measure: fewer slips from today’s error log.']];
'''
s=s[:b0]+detail+s[b1:]
rep=[
("['Stage 6 answers come too easily (the student guesses).','Answer only well-formed questions; the facts stay off-screen.'],",
 "['Stage 6 answers come too easily (the student guesses).','Answer only the information requested, and only well-formed questions; the six facts stay off-screen.'],\n ['Round 2 becomes a mechanical questionnaire.','Choose 3–4 questions and add natural follow-ups (Every day? How often? Do you like working there?).'],"),
("<div class=\"card\"><div class=\"k\" style=\"color:var(--or)\">A · Dr. Sarah (stage 6 — do not show)</div>${D.SARAH.facts.map(",
 "<div class=\"card\"><div class=\"k\" style=\"color:var(--or)\">A · Dr. Sarah — central character</div><p style=\"margin-top:1.4mm\" class=\"ink\">Stage 3 (on screen): ${D.SARAH.day.map(([t,k,p])=>t+' '+p).join(' · ')}</p><div class=\"k\" style=\"margin-top:2.5mm\">Stage 6 — teacher only, do not show</div>${D.SARAH.facts.map("),
("<div class=\"card\"><div class=\"k\" style=\"color:var(--or)\">A · Dr. Ben (stage 8, Round 1 — do not show)</div>${D.BEN.facts.map(([k,v])=>`<p style=\"margin-top:1.4mm\"><span class=\"ink\">${q(k)}</span> — ${q(v)}</p>`).join('')}</div>",
 "<div class=\"card\"><div class=\"k\" style=\"color:var(--or)\">A · Dr. Ben — Dr. Sarah’s colleague (Stage 8, Round 1 only — do not show)</div>${['Dr. Ben works at a hospital.','He starts at 8:00 in the evening.','He works at night.','He sees about 20 patients a night.','He works on weekends.','He doesn’t work on Mondays.','He finishes at 6:00 in the morning.'].map(v=>`<p style=\"margin-top:1.4mm\">${v}</p>`).join('')}<p class=\"ink\" style=\"margin-top:1.4mm\">Answer only what is asked, in the 3rd person.</p></div>"),
("['Materials','01 Student PPTX (17 slides, teacher notes in speaker notes) · 02 Student PDF (6 pages) · this plan (error log in Appendix C)']",
 "['Characters','Dr. Sarah — central fictional doctor (stages 3 and 6) · Dr. Ben — her colleague (stage 8, Round 1 only)'],['Materials','01 Student PPTX REV1.1 (17 slides, teacher notes in speaker notes) · 02 Student PDF REV1.1 (6 pages) · this plan (error log in Appendix C)']"),
("Frequency adverbs — always · usually · sometimes · never — and “How often do you work on weekends? / How often do you see patients?” Build it from this lesson’s error log. Not taught today.",
 "Frequency adverbs — always · usually · sometimes · never — and “How often do you work on weekends? / How often do you see patients?” Build it from this lesson’s error log. Shown only as a small preview on slide 17 — do not teach it now."),
]
for a,b in rep:
    assert a in s,a[:80]; s=s.replace(a,b)
open('docs.js','w').write(s); print('ok')
